DROP TABLE IF EXISTS `customers`;

CREATE TABLE IF NOT EXISTS `customers` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(40) DEFAULT NULL,
    `surname` VARCHAR(40) DEFAULT NULL,
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `item`;

CREATE TABLE IF NOT EXISTS `item` (
	`id` BIGINT AUTO_INCREMENT,
    `product_name` VARCHAR(64) NOT NULL UNIQUE,
    `price` DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (`id`)
);





